### PR TITLE
Feature: add initial example subscription module

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

This adds a new example subscription module to `onsite-example-test-gateway`.  This does not yet include every possible method, but aims to show how to get started.  We will iteratively add more to the subscription module as stability of the framework increases.

## Affects

- `onsite-example-test-gateway` now supports subscriptions (recurring donations)

## Visuals

Screenshot 2023-11-02 at 1 12 55 PM

## Testing Instructions

- Go to payment gateway settings and enable the onsite test gateway
- Setup a form for recurring donations
- Use the onsite test gateway 

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by JasonTheAdams — COMMENTED** [review]
@jonwaldstein I wouldn't actually recommend 3rd parties to use subscription modules. We only use them because we want to separate out the recurring logic into a separate add-on. I don't think most 3rd parties will do this. We built the whole system such that you can put all the recurring logic into your gateway class without a module.

**Comment by jonwaldstein** [comment]
@JasonTheAdams the reason i'm adding the subscription module here is because it's much easier to show the subscription specific apis inside a subscription module rather than everything being in one class.  This is actually the reason I _would_ recommend third parties use a subscription module because all their logic can be isolated - which as we know is always more complicated to deal with than one-time payments. 

Although it's potentially more convenient to add subscription logic inside the main gateway class, in my experience - it also comes with the cost of being harder to maintain as the file grows substantially.

**Comment by dightinfotechcom** [comment]
Hi 

Like I am getting response in js from hosted checkout which is working for one time
`{status: true, message: 'Payment processed successfully. ', charge_id: 'cha_655b5718518dd5064', data: 'NA', subscription_id: 'sub_655b571abf5325064'}`

Now I want to use this response for subscription
But I couldn't send this in php. I tried the ajax but nothing happened. 
how can I pass those response in php
```
what is "id" for here?
 public static function createSubscription(array $data): array
    {
         return array_merge([
            'id' => uniqid('egsub_', true),
            'transaction_id' => '1234567890',
        ], $data);
    }
```

**Comment by JasonTheAdams** [comment]
> @JasonTheAdams the reason i'm adding the subscription module here is because it's much easier to show the subscription specific apis inside a subscription module rather than everything being in one class. This is actually the reason I _would_ recommend third parties use a subscription module because all their logic can be isolated - which as we know is always more complicated to deal with than one-time payments.
> 
> Although it's potentially more convenient to add subscription logic inside the main gateway class, in my experience - it also comes with the cost of being harder to maintain as the file grows substantially.

What you're describing is best practice of code organization, which isn't really the point of our subscription modules. A developer could choose to take the class and break it up into traits or whatever, to organize it however they please. The subscription module exists purely for the ability to define classes in two different code bases and connect them, which I don't think is a scenario we need to bring to folks attention — at least not as the default. The simplest way to make a Gateway is a single class, and devs can break that up however they please to organize their code.

**Comment by jonwaldstein** [comment]
@JasonTheAdams 
>What you're describing is best practice of code organization, which isn't really the point of our subscription modules.

While I agree with this, I also think subscription modules + code organization is a happy accident 😄.  

Probably the biggest selling point for me right now is that Subscription Modules are the most stable version of recurring support.  All of our recurring gateways in production are being used with the subscription module approach.  Although we put effort into making it _possible_ for gateways to add support within their main class - we are only confident in its theoretical approach.  There are still some nuances about going this route that are unknown that I would hesitate to publicly document without actually putting to the test.

Aside from simply placing the methods in the main gateway class vs the subscription module, I have other concerns.  
1. Inside the main gateway class, every subscription method is an override.  This becomes a little dance for our framework to ensure both the abstract class and the parent class are compatible with the underlying interface.  We ran into this [situation](https://github.com/impress-org/givewp/pull/6695) a while back
2. By default, our abstract gateway class assumes a subscription module for its subscription logic.  This philosophically means it's the first class way of supplying recurring support.  Although we have conditional logic for _some_ subscription related methods, it's not completely [consistent](https://github.com/impress-org/givewp/blob/6bb1971eb9d03fc74ec26320837ef06cdbf226b1/src/Framework/PaymentGateways/PaymentGateway.php#L136).  This goes back to requiring overrides, in which your point below could be misleading as the modules _are_ the default.

>The subscription module exists purely for the ability to define classes in two different code bases and connect them, which I don't think is a scenario we need to bring to folks attention — at least not as the default.


I guess in the end, i'm not yet confident in the gateway class approach and i'm hesitant to recommend it publicly.  Some of my confidence could be earned back with more discussion and practical testing so feel free to debate with me verbally 🧙

**Comment by jonwaldstein** [comment]
Merging for now with plans to create a more realistic gateway example in the near future.

**Pull request merged**
